color: null
description: null
fieldLayouts:
  65a82dfe-6080-465e-bb47-7c2cdaabdba2:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        name: Content
        uid: 7ea8807e-82d1-408a-bcd0-6b0e6cb1ad8f
        userCondition: null
handle: asideParagraph
hasTitleField: false
icon: align-right
name: 'Aside Paragraph'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
