color: null
description: null
fieldLayouts:
  02f2aec1-b560-491d-b6ef-2bda4dc34903:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        name: Content
        uid: 52498aa0-4b32-4dec-afb7-81ad666eabb2
        userCondition: null
handle: billboardSplit
hasTitleField: false
icon: billboard
name: 'Billboard Split'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
