color: null
description: null
fieldLayouts:
  13004682-0f44-48b8-bc50-67c5ed58ce58:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        name: Content
        uid: 126465ae-b60f-47b0-b5b0-87a7a56414b7
        userCondition: null
handle: editorialColumns
hasTitleField: false
icon: newspaper
name: 'Editorial Columns'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
