columnSuffix: null
handle: pageBlocks
instructions: null
name: 'Page Blocks'
searchable: false
settings:
  createButtonLabel: 'Add Elements'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - d4e862fe-3c55-483a-a924-52c46e7ddd5d # Content
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
