currLabel: Client
customIcon: null
enabled: true
handle: client
icon: null
layout: 161e35c5-199b-4d9c-b090-9dc1c61bc616 # Default
level: 1
newWindow: false
parent: null
prevLabel: Client
prevLevel: null
prevParent: null
prevUrl: null
sortOrder: 0
type: divider
url: null
