currLabel: Pages
customIcon: null
enabled: true
handle: entries
icon: newspaper
layout: 161e35c5-199b-4d9c-b090-9dc1c61bc616 # Default
level: 1
newWindow: false
parent: null
prevLabel: Entries
prevLevel: 1
prevParent: null
prevUrl: entries
sortOrder: 1
type: craft
url: entries
