currLabel: GraphiQL
customIcon: null
enabled: true
handle: graphiql
icon: null
layout: 161e35c5-199b-4d9c-b090-9dc1c61bc616 # Default
level: 2
newWindow: true
parent: 86963631-ab2b-409f-9f3e-83e7c91f7084
prevLabel: GraphiQL
prevLevel: 2
prevParent: 86963631-ab2b-409f-9f3e-83e7c91f7084
prevUrl: graphiql
sortOrder: 6
type: craft
url: graphiql
