currLabel: GraphQL
customIcon: null
enabled: false
handle: graphql
icon: graphql
layout: 161e35c5-199b-4d9c-b090-9dc1c61bc616 # Default
level: 1
newWindow: false
parent: null
prevLabel: GraphQL
prevLevel: 1
prevParent: null
prevUrl: graphql
sortOrder: 3
type: craft
url: graphql
