currLabel: Schemas
customIcon: null
enabled: true
handle: schemas
icon: null
layout: 161e35c5-199b-4d9c-b090-9dc1c61bc616 # Default
level: 2
newWindow: false
parent: 86963631-ab2b-409f-9f3e-83e7c91f7084
prevLabel: Schemas
prevLevel: 2
prevParent: 86963631-ab2b-409f-9f3e-83e7c91f7084
prevUrl: graphql/schemas
sortOrder: 2
type: craft
url: graphql/schemas
