currLabel: Utilities
customIcon: null
enabled: true
handle: utilities
icon: wrench
layout: 161e35c5-199b-4d9c-b090-9dc1c61bc616 # Default
level: 1
newWindow: false
parent: null
prevLabel: Utilities
prevLevel: 1
prevParent: null
prevUrl: utilities
sortOrder: 8
type: craft
url: utilities
