defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 7f030e40-f1e9-4283-ae32-cc39aad9dd6b # pageStandard
handle: pages
maxAuthors: 1
name: Pages
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  48eabee0-5886-430a-ac24-e708a30e425a: # Filament-Boilerplate
    enabledByDefault: true
    hasUrls: true
    template: page.twig
    uriFormat: '{slug}'
structure:
  maxLevels: null
  uid: 2ed93057-e98e-4642-8052-7d22a104db17
type: structure
