name: Filament-Boiler
type: craftcms
docroot: web
php_version: "8.3"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mysql
    version: "8.0"
use_dns_when_possible: true
composer_version: "2"
web_environment: []
corepack_enable: false
default_container_timeout: "240"
web_extra_exposed_ports:
    - name: craft-vite
      container_port: 5173
      http_port: 5172
      https_port: 5173
